# Generated by Django 4.1.1 on 2022-12-06 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='box',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answers_boxes', to='question_box.boxes'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='timestamp',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='answered_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answers_user', to='question_box.newuser'),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='asked_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='asks_user', to='question_box.newuser'),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='confirmed_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comfirms_user', to='question_box.newuser'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='box',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions_boxes', to='question_box.boxes'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='timestamp',
            field=models.DateTimeField(default=None),
        ),
    ]
