# Generated by Django 4.1.1 on 2022-12-06 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0002_alter_answers_box_alter_answers_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='box',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='question_box.boxes'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='box',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question_box.boxes'),
        ),
    ]
