# Generated by Django 4.1.1 on 2022-12-06 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0003_alter_answers_box_alter_questions_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='box',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='question_box.boxes'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='comfirmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='answered_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_user', to='question_box.newuser'),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='asked_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asks_user', to='question_box.newuser'),
        ),
        migrations.AlterField(
            model_name='boxes',
            name='confirmed_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comfirms_user', to='question_box.newuser'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_type',
            field=models.CharField(default='user', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='anonymous',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='box',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question_box.boxes'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='post',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='public',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
