# Generated by Django 4.1.1 on 2022-12-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0004_alter_answers_answer_alter_answers_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxes',
            name='answered',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
