# Generated by Django 4.1.1 on 2022-12-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0005_boxes_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='comfirmed',
        ),
        migrations.AddField(
            model_name='boxes',
            name='comfirmed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
