# Generated by Django 4.1.1 on 2022-12-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0006_remove_answers_comfirmed_boxes_comfirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxes',
            old_name='comfirmed',
            new_name='confirmed',
        ),
    ]
