# Generated by Django 4.1.1 on 2022-12-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0007_rename_comfirmed_boxes_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxes',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='answers',
            name='confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
