# Generated by Django 4.1.1 on 2022-12-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0008_remove_boxes_confirmed_answers_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='edited',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='edited',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
