# Generated by Django 4.1.1 on 2023-06-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0009_answers_edited_questions_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxes',
            name='topic',
            field=models.TextField(default='family', null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='topic',
            field=models.TextField(default='family', null=True),
        ),
    ]
