# Generated by Django 4.1.1 on 2023-06-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0010_boxes_topic_newuser_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='post',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
